version: 0.2
phases:
  build:
    commands:
      - cd elasticbeanstalk/demo
      - mvn -q clean package

  post_build:
    commands:
      # you're already in elasticbeanstalk/demo, so COPY from target...
      - cp target/sample.war $CODEBUILD_SRC_DIR



artifacts:
  files:
    - sample.war
  discard-paths: yes
