version: 0.2
phases:
  build:
    commands:
      - cd elasticbeanstalk/demo
      - mvn -q clean package

  post_build:
    commands:
      - cp target/sample.war .


artifacts:
  files:
    - sample.war
  discard-paths: yes
