version: 0.2
phases:
  build:
    commands:
      - cd elasticbeanstalk/demo
      - mvn -q clean package
      - cd target
      - pwd
      - cp sample.war ../../../
      - cd ../../../
      - ls

artifacts:
  files:
    - sample.war
  discard-paths: yes
