version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing zip utility...
      - apt-get update && apt-get install -y zip

  build:
    commands:
      - echo Zipping Lambda function...
      - cd artifact-lab
      - zip ../function.zip app.py

artifacts:
  files:
    - function.zip
