version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update

  build:
    commands:
      - mv codedeploy-lab/app.py app.py
      - mv codedeploy-lab/appspec.yml appspec.yml

artifacts:
  files:
    - app.py
    - appspec.yml