version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd codebuild-lab
      - npm install
  build:
    commands:
      - cd codebuild-lab
      - node index.js

artifacts:
  files:
    - '**/*'
