version: 0.2

phases:
  build:
    commands:
      - echo "Checking for Lambda version..."
      - |
        if aws lambda get-function --function-name codedeploy-lab-function; then
          LAMBDA_VERSION=$(aws lambda list-versions-by-function --function-name codedeploy-lab-function --query 'Versions[-1].Version' --output text)
        else
          echo "Lambda function not found, using \$LATEST"
          LAMBDA_VERSION="\$LATEST"
        fi
      - |
        echo "version: 0.0" > codedeploy-lab/appspec.yml
        echo "Resources:" >> codedeploy-lab/appspec.yml
        echo "  - MyLambdaFunction:" >> codedeploy-lab/appspec.yml
        echo "      Type: AWS::Lambda::Function" >> codedeploy-lab/appspec.yml
        echo "      Properties:" >> codedeploy-lab/appspec.yml
        echo "        Name: codedeploy-lab-function" >> codedeploy-lab/appspec.yml
        echo "        Alias: live" >> codedeploy-lab/appspec.yml
        echo "        CurrentVersion: version-${LAMBDA_VERSION}" >> codedeploy-lab/appspec.yml


artifacts:
  files:
    - app.py
    - appspec.yml