version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update && apt-get install -y zip

  build:
    commands:
      - echo "Zipping Lambda function and appspec..."
      - zip -r function.zip codedeploy-lab/

artifacts:
  files:
    - function.zip
