version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update && apt-get install -y zip

  build:
    commands:
      - echo "Creating function.zip..."
      - zip function.zip codedeploy-lab/app.py codedeploy-lab/appspec.yml

artifacts:
  files:
    - function.zip

