version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update && apt-get install -y zip

  build:
    commands:
      - echo "Zipping app.py and appspec.yml into function.zip"
      - cd codedeploy-lab
      - zip ../function.zip app.py appspec.yml

  post_build:
    commands:
      - echo "Uploading function.zip to S3"
      - aws s3 cp ../function.zip s3://codedeploy-lab-8858/function.zip

