version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update && apt-get install -y zip

  build:
    commands:
      - mkdir artifact
      - cp codedeploy-lab/app.py artifact/
      - cp codedeploy-lab/appspec.yml artifact/

artifacts:
  # tell CodeBuild to zip the contents of "artifact/"
  files:
    - artifact/**
