version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update && apt-get install -y zip

  build:
    commands:
      - echo "Creating function.zip..."
      - zip function.zip codedeploy-lab/app.py codedeploy-lab/appspec.yml
      # Get the latest published Lambda version
      - LAMBDA_VERSION=$(aws lambda list-versions-by-function --function-name codedeploy-lab-function --query "Versions[-1].Version" --output text)

      # Build appspec.yml with dynamic version
      - cat > artifact/appspec.yml <<EOF
version: 0.0
Resources:
  - MyLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: codedeploy-lab-function
        Alias: live
        CurrentVersion: version-${LAMBDA_VERSION}
EOF

artifacts:
  files:
    - function.zip

